services:
  rabbitmq_cold_shutdown:
    container_name: rabbitmq_cold_shutdown
    image: rabbitmq:3.13.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=local_user
      - RABBITMQ_DEFAULT_PASS=local_password
    ports:
      - "15672:15672"

  celery_cold_shutdown:
    container_name: celery_cold_shutdown
    image: celery_cold_shutdown
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - REMAP_SIGTERM=SIGQUIT
    init: true
    depends_on:
      - rabbitmq_cold_shutdown
    command: celery -A mysite worker -l INFO -n celery -c 1 -P prefork -Q celery --without-heartbeat --without-mingle --without-gossip
    volumes:
      - .:/usr/src/app/
